### ISSUE TITLE
example run error:   in the android environment with changing the sdk dependency

### ISSUE THREAD

**Issue by hhstore** [weishirongzhen/flutter_trust_wallet_core#12]
## a PR here: 

- https://github.com/weishirongzhen/flutter_trust_wallet_core/pull/13

## env: 

- Android
- flutter 2.2.3
- use `implementation(name: 'trustwalletcore', ext: 'aar')` is ok(build + run)
- but use `implementation group: 'com.trustwallet', name: 'wallet-core', version: '2.6.3'`, build ok, run error.

## change sdk dependencies: 

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // implementation(name: 'trustwalletcore', ext: 'aar')
    // https://github.com/trustwallet/wallet-core
    // https://mvnrepository.com/artifact/com.trustwallet/wallet-core
    implementation group: 'com.trustwallet', name: 'wallet-core', version: '2.6.3'

}

```

## run error logs: 

- flutter 2.2.3

```

🕙 [2021-08-20 Fri 12:01:01] [🔴 ERROR] ✗  fvm flutter run -d bxxxx5
Launching lib/main.dart on Redmi K30 Pro in debug mode...
Running Gradle task 'assembleDebug'...                             69.1s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                25.9s
Syncing files to device Redmi K30 Pro...                           210ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Redmi K30 Pro is available at: http://127.0.0.1:64907/Z7WInxqjNKY=/
I/et_core_exampl(21013): ProcessProfilingInfo new_methods=463 is saved saved_to_disk=1 resolve_classes_delay=8000
The Flutter DevTools debugger and profiler on Redmi K30 Pro is available at: http://127.0.0.1:64912?uri=http%3A%2F%2F127.0.0.1%3A64907%2FZ7WInxqjNKY%3D%2F
E/flutter (21013): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (undefined symbol: TWStringCreateWithUTF8Bytes)
E/flutter (21013): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
E/flutter (21013): #1      TWString._TWStringCreateWithUTF8Bytes_ptr (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart:13:62)
E/flutter (21013): #2      TWString._TWStringCreateWithUTF8Bytes_ptr (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart)
E/flutter (21013): #3      TWString._TWStringCreateWithUTF8Bytes (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart:16:85)
E/flutter (21013): #4      TWString._TWStringCreateWithUTF8Bytes (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart)
E/flutter (21013): #5      TWString.TWStringCreateWithUTF8Bytes (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart:8:12)
E/flutter (21013): #6      TWStringImpl.toTWString (package:flutter_trust_wallet_core/dart_impl/tw_string_impl.dart:6:21)
E/flutter (21013): #7      TWHDWalletImpl.create (package:flutter_trust_wallet_core/dart_impl/tw_hd_wallet_impl.dart:6:46)
E/flutter (21013): #8      new HDWallet (package:flutter_trust_wallet_core/core/hd_wallet.dart:7:36)
E/flutter (21013): #9      _MyAppState.build.<anonymous closure> (package:flutter_trust_wallet_core_example/main.dart:82:44)
E/flutter (21013): #10     _MyAppState.build.<anonymous closure> (package:flutter_trust_wallet_core_example/main.dart:79:34)
E/flutter (21013): #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter (21013): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (21013): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter (21013): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (21013): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter (21013): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (21013): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter (21013): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter (21013): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (21013): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter (21013): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter (21013): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter (21013): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (21013): #24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter (21013): #25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (21013): #26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (21013): #27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (21013): #28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (21013): #29     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (21013): #30     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (21013): #31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (21013): #32     _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter (21013): #33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter (21013): #34     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter (21013):
E/flutter (21013): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (undefined symbol: TWStringCreateWithUTF8Bytes)
E/flutter (21013): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
E/flutter (21013): #1      TWString._TWStringCreateWithUTF8Bytes_ptr (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart:13:62)
E/flutter (21013): #2      TWString._TWStringCreateWithUTF8Bytes_ptr (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart)
E/flutter (21013): #3      TWString._TWStringCreateWithUTF8Bytes (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart:16:85)
E/flutter (21013): #4      TWString._TWStringCreateWithUTF8Bytes (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart)
E/flutter (21013): #5      TWString.TWStringCreateWithUTF8Bytes (package:flutter_trust_wallet_core/ffi_impl/tw_string.dart:8:12)
E/flutter (21013): #6      TWStringImpl.toTWString (package:flutter_trust_wallet_core/dart_impl/tw_string_impl.dart:6:21)
E/flutter (21013): #7      TWHDWalletImpl.create (package:flutter_trust_wallet_core/dart_impl/tw_hd_wallet_impl.dart:6:46)
E/flutter (21013): #8      new HDWallet (package:flutter_trust_wallet_core/core/hd_wallet.dart:7:36)
E/flutter (21013): #9      _MyAppState.build.<anonymous closure> (package:flutter_trust_wallet_core_example/main.dart:82:44)
E/flutter (21013): #10     _MyAppState.build.<anonymous closure> (package:flutter_trust_wallet_core_example/main.dart:79:34)
E/flutter (21013): #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter (21013): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (21013): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter (21013): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter (21013): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter (21013): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (21013): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter (21013): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter (21013): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (21013): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter (21013): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter (21013): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter (21013): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (21013): #24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter (21013): #25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (21013): #26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (21013): #27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (21013): #28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (21013): #29     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (21013): #30     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (21013): #31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (21013): #32     _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter (21013): #33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter (21013): #34     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter (21013):





```

**Comment by weishirongzhen** [comment]
current official lib is not compatible for this project.
